# Generated by Django 4.2.3 on 2023-07-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('release_date', models.DateTimeField()),
                ('lte_exists', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=20)),
            ],
        ),
    ]
